//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMS.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be empty..
        /// </summary>
        public static string ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address number cannot be empty..
        /// </summary>
        public static string ADDRESS_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP cannot be empty.
        /// </summary>
        public static string CEP_EMPTY {
            get {
                return ResourceManager.GetString("CEP_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP code is not valid..
        /// </summary>
        public static string CEP_INVALID {
            get {
                return ResourceManager.GetString("CEP_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ cannot be empty..
        /// </summary>
        public static string CNPJ_EMPTY {
            get {
                return ResourceManager.GetString("CNPJ_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNJP is not valid..
        /// </summary>
        public static string CNPJ_INVALID {
            get {
                return ResourceManager.GetString("CNPJ_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Company cannot be found, or does not exist..
        /// </summary>
        public static string COMPANY_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMPANY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        public static string CURRENT_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Business As cannot be empty..
        /// </summary>
        public static string DBA_EMPTY {
            get {
                return ResourceManager.GetString("DBA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of the trade name must be up to 100 characters..
        /// </summary>
        public static string DBA_MAX_LENGTH {
            get {
                return ResourceManager.GetString("DBA_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Cannot Be Empty..
        /// </summary>
        public static string DESCRIPTION_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("DESCRIPTION_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use by another user..
        /// </summary>
        public static string EMAIL_IN_USE {
            get {
                return ResourceManager.GetString("EMAIL_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email and/or password..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID cannot be empty..
        /// </summary>
        public static string EMPTY_COMPANY_ID {
            get {
                return ResourceManager.GetString("EMPTY_COMPANY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature must contain at least one property (benefit)..
        /// </summary>
        public static string EMPTY_PROPERTIES {
            get {
                return ResourceManager.GetString("EMPTY_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service type cannot be empty..
        /// </summary>
        public static string EMPTY_SERVICE_TYPE {
            get {
                return ResourceManager.GetString("EMPTY_SERVICE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service ID is blank..
        /// </summary>
        public static string EMPTY_SERVICES_ID {
            get {
                return ResourceManager.GetString("EMPTY_SERVICES_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A signature must be assigned..
        /// </summary>
        public static string EMPTY_SUBSCRIPTION_ID {
            get {
                return ResourceManager.GetString("EMPTY_SUBSCRIPTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot be empty..
        /// </summary>
        public static string EMPTY_TITLE {
            get {
                return ResourceManager.GetString("EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired token..
        /// </summary>
        public static string EXPIRED_TOKEN {
            get {
                return ResourceManager.GetString("EXPIRED_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty..
        /// </summary>
        public static string FIRST_NAME_EMPTY {
            get {
                return ResourceManager.GetString("FIRST_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token is not valid.
        /// </summary>
        public static string INVALID_ACCESS_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_ACCESS_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is not valid..
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is not valid..
        /// </summary>
        public static string INVALID_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value type..
        /// </summary>
        public static string INVALID_VALUE_TYPE {
            get {
                return ResourceManager.GetString("INVALID_VALUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is annual Billing cannot be empty..
        /// </summary>
        public static string IS_BILLING_ANNUAL_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("IS_BILLING_ANNUAL_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal name cannot be empty..
        /// </summary>
        public static string LEGAL_NAME_EMPTY {
            get {
                return ResourceManager.GetString("LEGAL_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Id cannot be empty..
        /// </summary>
        public static string MANAGER_ID_EMPTY {
            get {
                return ResourceManager.GetString("MANAGER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Id is not valid..
        /// </summary>
        public static string MANAGER_ID_INVALID {
            get {
                return ResourceManager.GetString("MANAGER_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Cannot Be Empty..
        /// </summary>
        public static string NAME_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("NAME_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission too low to perform this action..
        /// </summary>
        public static string NO_PERMISSION {
            get {
                return ResourceManager.GetString("NO_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no refresh token in the current request..
        /// </summary>
        public static string NO_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("NO_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token was found in the request..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length is invalid..
        /// </summary>
        public static string PASSWORD_LENGTH_IS_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone cannot be empty..
        /// </summary>
        public static string PHONE_EMPTY {
            get {
                return ResourceManager.GetString("PHONE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone is not valid..
        /// </summary>
        public static string PHONE_NOT_VALID {
            get {
                return ResourceManager.GetString("PHONE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plans were found with that id..
        /// </summary>
        public static string PLAN_NOT_FOUND {
            get {
                return ResourceManager.GetString("PLAN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid user with this refresh token..
        /// </summary>
        public static string REFRESH_TOKEN_NOT_FOUND {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role reported is not invalid..
        /// </summary>
        public static string ROLE_INVALID {
            get {
                return ResourceManager.GetString("ROLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço não encontrado..
        /// </summary>
        public static string SERVICE_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVICE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID (Sid) claim was not found in the token..
        /// </summary>
        public static string SID_CLAIM_NOT_FOUND {
            get {
                return ResourceManager.GetString("SID_CLAIM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered signature does not exist..
        /// </summary>
        public static string SUBSCRIPTION_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription plan type cannot be empty..
        /// </summary>
        public static string SUBSCRIPTION_PLAN_EMPTY {
            get {
                return ResourceManager.GetString("SUBSCRIPTION_PLAN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User context not found..
        /// </summary>
        public static string USER_CONTEXT_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_CONTEXT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have permission to access this resource..
        /// </summary>
        public static string USER_DOES_NOT_HAVE_PERMISSION {
            get {
                return ResourceManager.GetString("USER_DOES_NOT_HAVE_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user provided does not exist in our database..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
